# Generated by Django 3.1.2 on 2020-10-17 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Canonical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stockCount', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('modifiedTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modifiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alternateName', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Printers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaxRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('taxType', models.CharField(blank=True, max_length=100, null=True)),
                ('rate', models.IntegerField(default=0)),
                ('isDefault', models.BooleanField(default=False)),
                ('taxAmount', models.IntegerField(default=0)),
                ('deletedTime', models.DateTimeField(auto_now_add=True)),
                ('modifiedTime', models.DateTimeField(auto_now_add=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.items')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('showInReport', models.BooleanField(default=False)),
                ('printers', models.CharField(max_length=100)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.items')),
            ],
        ),
        migrations.CreateModel(
            name='ModifierGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alternateName', models.CharField(max_length=100)),
                ('minRequired', models.IntegerField(default=0)),
                ('maxAllowed', models.IntegerField(default=0)),
                ('showByDefault', models.BooleanField(default=True)),
                ('modifiers', models.ManyToManyField(to='inventory.Modifiers')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('alternateName', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('defaultTaxRates', models.BooleanField(default=True)),
                ('unitName', models.CharField(max_length=100)),
                ('cost', models.IntegerField(default=0)),
                ('isRevenue', models.BooleanField(default=False)),
                ('itemGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.itemgroup')),
                ('priceType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.pricetype')),
                ('taxRate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.taxrates')),
            ],
        ),
        migrations.CreateModel(
            name='ItemStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockCount', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('modifiedTime', models.DateTimeField(auto_now_add=True)),
                ('deletedTime', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.items')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sortOrder', models.IntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('modifiedTime', models.DateTimeField(auto_now_add=True)),
                ('canonical', models.ManyToManyField(to='inventory.Canonical')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.items')),
            ],
        ),
    ]
