# Generated by Django 3.1.2 on 2020-10-17 19:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='canonical',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.canonical'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='categories',
            field=models.ManyToManyField(to='inventory.Categories'),
        ),
        migrations.AddField(
            model_name='menu',
            name='deletedTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='menu',
            name='itemStock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemstock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='modifiedTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='menu',
            name='modifierGroups',
            field=models.ManyToManyField(to='inventory.ModifierGroups'),
        ),
        migrations.AddField(
            model_name='menu',
            name='options',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.options'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='tags',
            field=models.ManyToManyField(to='inventory.Tags'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='attribute',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canonical',
            name='canonical',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='modifiedTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='itemgroup',
            name='name',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='modifiedTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='itemstock',
            name='deletedTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='itemstock',
            name='modifiedTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='options',
            name='name',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pricetype',
            name='name',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='printers',
            name='printer',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxrates',
            name='deletedTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='taxrates',
            name='modifiedTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
